### ISSUE TITLE
rules are applied on 'build' or 'target' path by default if src/main or src/test is missing

### ISSUE THREAD

**Issue by paul58914080** [societe-generale/arch-unit-build-plugin-core#36]
### What is the issue ?

Assume we have a project structure like where you do not have **src/main**

![image](https://user-images.githubusercontent.com/10730990/84349288-9d60ba80-abd4-11ea-80c6-1587e64f489c.png)

when we use arch-unit plugin it defaults to `target` or `build` if **src/main** or **src/test** is missing

```
[WARNING] classpath /Users/paulwilliams/Desktop/WORKSPACE/DFM/hexagonal-spring-boot-java/acceptance-test/target/classes doesn't exist : loading all classes from root, ie /Users/paulwilliams/Desktop/WORKSPACE/DFM/hexagonal-spring-boot-java/acceptance-test/target even though it's probably not what you want to achieve..
[WARNING] existing folders and files under root project : 
[WARNING] target
```

In this case violations like `NoAutowiredFieldTest` fails because it is unable to know whether it is src/main or src/test. Even through it should be only for main class path https://github.com/societe-generale/arch-unit-build-plugin-core/blob/master/src/main/java/com/societegenerale/commons/plugin/rules/NoAutowiredFieldTest.java#L24

### How to produce ?

- Checkout code from https://github.com/devs-from-matrix/hexagonal-spring-boot-java
- `maven clean install`
- The logs should have the details

**Comment by vincent-fuchs** [comment]
the NoAutowiredFieldTest rule is indeed targeted mostly for "producton" code, as some teams are a little bit more lenient and accept the use of Autowired for tests.

When we load the classes to check, there's a possibility that the path doesn't exist, like in your case. But it's even more relevant with `configurableRule`, for which you can configure a rule to be applied only on a specific package.

From the rule's perspective, there are 2 possibilities here : 
1. fail almost silently
2. default to a "wider" location, with a warning message. 

we picked the second option - https://github.com/societe-generale/arch-unit-build-plugin-core/blob/master/src/main/java/com/societegenerale/commons/plugin/utils/ArchUtils.java#L39 , to avoid the case where the build is passing because the path is not configured and actually no class is inspected. 

So in your case, I see 2 solutions : 
- create an main/java folder with a DummyClass in it : it will get compiled, target/classes will exist, and the path is found 
- override the archnunit config in your acceptance-test module, so that the rules that are targeted for "production code" don't apply here.

**Comment by paul58914080** [comment]
- 1st solution seems like a hack and I did the same but with dummy interface
- How do you propose to do _override the archnunit config in your acceptance-test module, so that the rules that are targeted for "production code" don't apply here._

I believed `configurableRules = [configurableRule("com.tngtech.archunit.library.GeneralCodingRules", applyOn("de.gefa.packagename", "main"))]` should be only on main but it isnt the case. Is there any other way ?

**Comment by vincent-fuchs** [comment]
I assume you have declared the rules at top level of your project, so that they apply to all of your modules. 

if you redefine it in a given module, it should override the top level config. So in your module, you could have this : 

```
   <plugin>
        <groupId>com.societegenerale.commons</groupId>
        <artifactId>arch-unit-maven-plugin</artifactId>
        <version>${arch-unit-maven-plugin.version}</version>
        <configuration>
          <projectPath>${project.basedir}/target</projectPath>
          <rules>
            <preConfiguredRules>
              <rule>com.societegenerale.commons.plugin.rules.NoJunitAssertRuleTest</rule>
              <rule>com.societegenerale.commons.plugin.rules.NoPowerMockRuleTest</rule>
              <rule>com.societegenerale.commons.plugin.rules.NoTestIgnoreRuleTest</rule>
              <rule>com.societegenerale.commons.plugin.rules.NoTestIgnoreWithoutCommentRuleTest</rule>
            </preConfiguredRules>
          </rules>
        </configuration>
        <executions>
          <execution>
            <phase>test</phase>
            <goals>
              <goal>arch-test</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

would that work ?
